name: openapi_repository
description: This package generates ListBloc and DataBloc using openapi_repository_annotations.
version: 1.1.0
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^5.2.0
  build: ^2.3.0
  built_collection: ^5.1.1
  built_value: ^8.3.2
  collection: ^1.16.0
  dio: ^5.0.2
  freezed_annotation: ^2.0.3
  list_bloc: ^3.1.0
  mustache_template: ^2.0.0
  openapi_repository_annotations: ^1.1.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.16.0
