name: flutter_list_bloc
description: A Flutter package to display the data loaded with list_bloc.
version: 2.0.1
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  list_bloc: ^2.0.1
  flutter_bloc: ^7.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
