name: flutter_list_bloc
description: A Flutter package to display the data loaded with list_bloc.
version: 1.0.3
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  list_bloc: ^1.0.2
  flutter_bloc: ^6.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
