name: list_bloc
description: A BLoC library for loading data from an api end-point with filtering and pagination.
version: 3.0.3
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
