name: list_bloc
description: A BLoC library for loading data from an api end-point with filtering and pagination.
version: 0.0.5
homepage: https://github.com/apexlabs-ai/list_bloc/packages/list_bloc

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  bloc: ^4.0.0
  equatable: ^1.2.0
#  built_value: ^7.1.0


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
#  build_runner: ^1.10.0
#  built_value_generator: ^7.1.0
