name: list_bloc
description: A BLoC library for loading data from an api end-point with filtering and pagination.
version: 2.0.2
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
