name: list_bloc
description: A BLoC library for loading data from an api end-point with filtering and pagination.
version: 3.0.0-dev1
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  freezed_annotation: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
  build_runner: ^2.1.8
  freezed: ^1.1.1
